services:
  - type: web
    name: emotion-aware-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: sqlite:///app.db
      - key: SECRET_KEY
        generateValue: true
      - key: MODEL_NAME
        value: SamLowe/roberta-base-go_emotions
      - key: DEVICE
        value: cpu
      - key: MAX_LENGTH
        value: 512
    disk:
      name: data
      mountPath: /data
      sizeGB: 1